version: '3'

x-docker:
  &project_name modern_dental_data_demo

services:

  billing_and_payment:
    build:
      context: ./Database_Services/billing_and_payment
      dockerfile: Dockerfile
    links:
      - "mysql:localhost"
    image: billing_and_payment
    container_name: billing_and_payment-container
    depends_on:
      - mysql
    networks:
      - custom_network


  inventory_and_supplies:
    build:
      context: ./Database_Services/inventory_and_supplies
      dockerfile: Dockerfile
    links:
      - "mysql:localhost"
    image: inventory_and_supplies
    container_name: inventory_and_supplies-container
    depends_on:
      - mysql
    networks:
      - custom_network

  patient_crm:
    build:
      context: ./Database_Services/patient_crm
      dockerfile: Dockerfile
    links:
      - "mysql:localhost"
    image: patient_crm
    container_name: patient_crm-container
    depends_on:
      - mysql
    networks:
      - custom_network

  staff_management:
    build:
      context: ./Database_Services/staff_management
      dockerfile: Dockerfile
    links:
      - "mysql:localhost"
    image: staff_management
    container_name: staff_management-container
    depends_on:
      - mysql
    networks:
      - custom_network


  mysql:
    image: mysql:latest
    container_name: mysql-container
    command: --init-file /data/application/init.sql
    volumes:
        - ./init.sql:/data/application/init.sql
        - mysql-data:/var/lib/mysql
    env_file:
      - .env
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 3
    networks:
      - custom_network
    ports:
      - "3306:3306"

  
volumes:
  mysql-data:

networks:
  custom_network:
    driver: bridge
    name: modern_data_network