version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container-billing
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ALLOW_PUBLIC_KEY_RETRIEVAL: 'True'
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 3
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  
volumes:
  mysql-data:
