name: Deploy dbt
on:
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Set working directory
        run: cd elt_jobs
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run test hello
        run: python workflow_test.py
